//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHSBackOffice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CHSBackOffice.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Floats.
        /// </summary>
        internal static string ActiveFloatsTitle {
            get {
                return ResourceManager.GetString("ActiveFloatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parameter.
        /// </summary>
        internal static string AddParameterTitle {
            get {
                return ResourceManager.GetString("AddParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Transactions.
        /// </summary>
        internal static string AllTransactionsTitle {
            get {
                return ResourceManager.GetString("AllTransactionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can contain digits only.
        /// </summary>
        internal static string ArentDigits {
            get {
                return ResourceManager.GetString("ArentDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to set &apos;.
        /// </summary>
        internal static string AreYouSureSetStartPage {
            get {
                return ResourceManager.GetString("AreYouSureSetStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to switch host url?.
        /// </summary>
        internal static string AreYouSureSwitchUrl {
            get {
                return ResourceManager.GetString("AreYouSureSwitchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; as Start Page ?.
        /// </summary>
        internal static string AsStartPage {
            get {
                return ResourceManager.GetString("AsStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-refresh machine status info.
        /// </summary>
        internal static string AutoRefreshText {
            get {
                return ResourceManager.GetString("AutoRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK OFFICE.
        /// </summary>
        internal static string BackOffice {
            get {
                return ResourceManager.GetString("BackOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the maximum number of bundles for a Bill Breaking transaction, from &quot;1&quot; to &quot;n&quot; where &quot;n&quot; has no limit.
        /// </summary>
        internal static string BBMaxBundles {
            get {
                return ResourceManager.GetString("BBMaxBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specefies the maximum receiving denomination for Bill Breaking in cents (ex. $1 = 100)..
        /// </summary>
        internal static string BBMaxDenonimation {
            get {
                return ResourceManager.GetString("BBMaxDenonimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the minimum number of bundles for a Bill Breaking transaction, from &quot;1&quot; to &quot;n&quot; where &quot;n&quot; has no limit.
        /// </summary>
        internal static string BBMinBundles {
            get {
                return ResourceManager.GetString("BBMinBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specefies the minimum receiving denomination for Bill Breaking in cents (ex. $1 = 100)..
        /// </summary>
        internal static string BBMinDenonimation {
            get {
                return ResourceManager.GetString("BBMinDenonimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Breaking Rule #2 for $20.
        /// </summary>
        internal static string BBRule20_2 {
            get {
                return ResourceManager.GetString("BBRule20_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a receiving currency that is used for Bill Breaking transactions.
        /// </summary>
        internal static string BillBreaking {
            get {
                return ResourceManager.GetString("BillBreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is enabled in order to process Bill Breaking transactions.
        /// </summary>
        internal static string BillBreakingEnable {
            get {
                return ResourceManager.GetString("BillBreakingEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILL VAL..
        /// </summary>
        internal static string BillVal {
            get {
                return ResourceManager.GetString("BillVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH DIS..
        /// </summary>
        internal static string CashDis {
            get {
                return ResourceManager.GetString("CashDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Dispenser.
        /// </summary>
        internal static string CashDispenser {
            get {
                return ResourceManager.GetString("CashDispenser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash On Hand.
        /// </summary>
        internal static string CashOnHandTitle {
            get {
                return ResourceManager.GetString("CashOnHandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Utilization.
        /// </summary>
        internal static string CashUtilizationTitle {
            get {
                return ResourceManager.GetString("CashUtilizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause of Error.
        /// </summary>
        internal static string CauseOfError {
            get {
                return ResourceManager.GetString("CauseOfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 4 to 15 character long..
        /// </summary>
        internal static string CharacterLongError {
            get {
                return ResourceManager.GetString("CharacterLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Hopper.
        /// </summary>
        internal static string CoinHopper {
            get {
                return ResourceManager.GetString("CoinHopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COINS DIS..
        /// </summary>
        internal static string CoinsDis {
            get {
                return ResourceManager.GetString("CoinsDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enter to confirm.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword2 {
            get {
                return ResourceManager.GetString("ConfirmPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackOffice.
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Amount.
        /// </summary>
        internal static string DepositAmount {
            get {
                return ResourceManager.GetString("DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device and Interface Version.
        /// </summary>
        internal static string DeviceAndInterfaceVersion {
            get {
                return ResourceManager.GetString("DeviceAndInterfaceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door Open Events.
        /// </summary>
        internal static string DoorOpenEventsTitle {
            get {
                return ResourceManager.GetString("DoorOpenEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit parameter.
        /// </summary>
        internal static string EditParameterTitle {
            get {
                return ResourceManager.GetString("EditParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notification status.
        /// </summary>
        internal static string EmailNotyfyStatus {
            get {
                return ResourceManager.GetString("EmailNotyfyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Managment Page.
        /// </summary>
        internal static string EmployeeManagmentTitle {
            get {
                return ResourceManager.GetString("EmployeeManagmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string EmployeesTitle {
            get {
                return ResourceManager.GetString("EmployeesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint not found.
        /// </summary>
        internal static string EndpointNotFound {
            get {
                return ResourceManager.GetString("EndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Descriptions.
        /// </summary>
        internal static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Filter.
        /// </summary>
        internal static string EventsFilterTitle {
            get {
                return ResourceManager.GetString("EventsFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string EventsTitle {
            get {
                return ResourceManager.GetString("EventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Timestamp.
        /// </summary>
        internal static string EventTimestamp {
            get {
                return ResourceManager.GetString("EventTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one upper case(A-Z), one number(0-9)..
        /// </summary>
        internal static string HasNotNumberUpperChar {
            get {
                return ResourceManager.GetString("HasNotNumberUpperChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host URL has been updated successfully..
        /// </summary>
        internal static string HostURLUpdated {
            get {
                return ResourceManager.GetString("HostURLUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore server certificate.
        /// </summary>
        internal static string IgnoreCertText {
            get {
                return ResourceManager.GetString("IgnoreCertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Host address for your CHS \r\n BackOffice mobile screen.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Current Password.
        /// </summary>
        internal static string InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Availability.
        /// </summary>
        internal static string MachineAvailabilityTitle {
            get {
                return ResourceManager.GetString("MachineAvailabilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Status.
        /// </summary>
        internal static string MachineStatusTitle {
            get {
                return ResourceManager.GetString("MachineStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        internal static string NetAmount {
            get {
                return ResourceManager.GetString("NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Active Float Found.
        /// </summary>
        internal static string NoActiveFloatFound {
            get {
                return ResourceManager.GetString("NoActiveFloatFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Available.
        /// </summary>
        internal static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to server.
        /// </summary>
        internal static string NoInternetText {
            get {
                return ResourceManager.GetString("NoInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Machine Parameters Available.
        /// </summary>
        internal static string NoMachineParametersAvailable {
            get {
                return ResourceManager.GetString("NoMachineParametersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter-Add.
        /// </summary>
        internal static string ParameterAdd {
            get {
                return ResourceManager.GetString("ParameterAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter-Update.
        /// </summary>
        internal static string ParameterUpdate {
            get {
                return ResourceManager.GetString("ParameterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully.
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password does not match, please re-enter.
        /// </summary>
        internal static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter  .
        /// </summary>
        internal static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Host URL.
        /// </summary>
        internal static string PleaseEnterHostUrl {
            get {
                return ResourceManager.GetString("PleaseEnterHostUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter login.
        /// </summary>
        internal static string PleaseEnterLogin {
            get {
                return ResourceManager.GetString("PleaseEnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        internal static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter URL.
        /// </summary>
        internal static string PleaseEnterURL {
            get {
                return ResourceManager.GetString("PleaseEnterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States when to print a Bill Breaking transaction on the receipt.
        /// </summary>
        internal static string PrintReceiptBB {
            get {
                return ResourceManager.GetString("PrintReceiptBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycler.
        /// </summary>
        internal static string Recycler {
            get {
                return ResourceManager.GetString("Recycler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control.
        /// </summary>
        internal static string RemoteControlTitle {
            get {
                return ResourceManager.GetString("RemoteControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Host URL.
        /// </summary>
        internal static string SaveHostURL {
            get {
                return ResourceManager.GetString("SaveHostURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Parameter Name.
        /// </summary>
        internal static string SelectParameterName {
            get {
                return ResourceManager.GetString("SelectParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Start Page.
        /// </summary>
        internal static string SelectStartPage {
            get {
                return ResourceManager.GetString("SelectStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Host URL.
        /// </summary>
        internal static string SetHostURLString {
            get {
                return ResourceManager.GetString("SetHostURLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: You will be signed out .
        /// </summary>
        internal static string SignedOut {
            get {
                return ResourceManager.GetString("SignedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Users.
        /// </summary>
        internal static string SOPUsersTitle {
            get {
                return ResourceManager.GetString("SOPUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start page has been updated to .
        /// </summary>
        internal static string StartPageUpdated {
            get {
                return ResourceManager.GetString("StartPageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameters.
        /// </summary>
        internal static string SystemParametersTitle {
            get {
                return ResourceManager.GetString("SystemParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the server is taking too long to respond, please try again in some while.
        /// </summary>
        internal static string TimeoutAlertText {
            get {
                return ResourceManager.GetString("TimeoutAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction By Type.
        /// </summary>
        internal static string TransactionByTypeTitle {
            get {
                return ResourceManager.GetString("TransactionByTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Details.
        /// </summary>
        internal static string TransactionDetailsTitle {
            get {
                return ResourceManager.GetString("TransactionDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string TransactionFilterTitle {
            get {
                return ResourceManager.GetString("TransactionFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Details.
        /// </summary>
        internal static string TransactionInfoTitle {
            get {
                return ResourceManager.GetString("TransactionInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string TransactionsTitle {
            get {
                return ResourceManager.GetString("TransactionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsupported URL.
        /// </summary>
        internal static string UnsupportedURL {
            get {
                return ResourceManager.GetString("UnsupportedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UsersTitle {
            get {
                return ResourceManager.GetString("UsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to change password?.
        /// </summary>
        internal static string WantToChangePassword {
            get {
                return ResourceManager.GetString("WantToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal.
        /// </summary>
        internal static string Withdrawal {
            get {
                return ResourceManager.GetString("Withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal Amount.
        /// </summary>
        internal static string WithdrawalAmount {
            get {
                return ResourceManager.GetString("WithdrawalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
